mysite/mysite/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
	url(r'^polls/', include('polls.urls')),
    url(r'^players/', include('players.urls')),
    url(r'^admin/', admin.site.urls),
]

mysite/players/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf.urls.static import static

from . import views
app_name="players"
urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^add$', views.CreateView.as_view(success_url="/players/"), name='add'),
    url(r'players/(?P<pk>[0-9]+)/$', views.PlayerUpdate.as_view(success_url="/players/"), name='player_update'),
    url(r'^delete/(?P<pk>[0-9]+)/$', views.PlayerDelete.as_view(success_url="/players/"), name='player_delete'),
]

mysite/polls/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from .import views
app_name = 'polls'
urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail'),
    #url(r'^(?P<pk>[0-9]+)/results/$', views.ResultsView.as_view(), name='results'),
    url(r'^(?P<question_id>[0-9]+)/results/$', views.results_page, name='results'),
    url(r'^(?P<question_id>[0-9]+)/vote/$', views.vote, name='vote'),
]

mysite/players/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
import datetime
from django.db import models

# Create your models here.

class Player(models.Model):
    player_name=models.CharField(max_length=200)
    forename = models.CharField(max_length=200)
    shirt_number=models.IntegerField(default=0)
    date_joined= models.DateField('When they joined the club')
    player_age=models.IntegerField(default=0)
    player_position = models.CharField(max_length=200)
    goals_this_season = models.IntegerField(default=0)
    def __str__(self):
        return str (self.player_name)

mysite/polls/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
import datetime
from django.shortcuts import get_object_or_404
from django.db import models
from django.utils import timezone
from players.models import Player

# Create your models here.
class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')
    def __str__(self):
        return self.question_text
    def was_published_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)
    def __str__(self):
        return self.choice_text


def topChoice(key):
    """
    Runs a for loop to determine the field with the most votes and returns it
    :return: returns the text value corresponding to the field with the most votes
    """
    # q = get_object_or_404(Question, pk=key)
    high_choice = 0
    high_text = None
    # i = 1
    for c in Choice.objects.filter(question=key):
        if c.votes > high_choice:
            high_choice = c.votes
            high_text = c.choice_text
			
			
    return high_text

mysite/players/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.http import HttpResponse, HttpResponseRedirect
from .models import Player
from django.shortcuts import render, get_object_or_404, redirect
from django.views import generic
from django.urls import reverse_lazy

# Create your views here.
class IndexView(generic.ListView):
    template_name = 'players/index.html'
    context_object_name = 'player_list'
    def get_queryset(self):
        """
        Return the player objects (not including those set to be
        published in the future).
        """
        return Player.objects.all()
class CreateView(generic.CreateView):
    template_name = "players/add_player.html"
    model = Player
    fields = "__all__"

class PlayerDelete(generic.DeleteView):
    model = Player
    template_name="players/confirm_delete.html"
# def player_delete(request, pk, template_name='players/confirm_delete.html'):
#     server = get_object_or_404(Player, pk=pk)
#     if request.method=='POST':
#         server.delete()
#         return redirect('IndexView', )
#     return render(request, template_name, {'object':server})

class PlayerUpdate (generic.UpdateView):
    model = Player
    fields="__all__"
    template_name = "players/update_form.html"
#writing a view as an edit
#class Editview(generic.)

mysite/polls/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from .models import Choice, Question
from django.urls import reverse
from django.views import generic
from django.utils import timezone
from polls.models import topChoice

# Create your views here.


class IndexView(generic.ListView):
    template_name = 'polls/index.html'
    context_object_name = 'latest_question_list'

    def get_queryset(self):
        """
        Return the last five published questions (not including those set to be
        published in the future).
        """
        return Question.objects.filter(
            pub_date__lte=timezone.now()
        ).order_by('-pub_date')[:5]

class DetailView(generic.DetailView):
    queryset = Question.objects.select_related()
    template_name = 'polls/detail.html'

# class ResultsView(generic.DetailView):
#     model = Question
#     template_name = 'polls/results.html'
#     #highAnswer = topChoice()

def results_page(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    high_answer = topChoice(question_id)
    return render(request, 'polls/results.html', {'question': question, 'high_text': topChoice(question_id)})

def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the question voting form.
        return render(request, 'polls/detail.html', {
            'question': question,
            'error_message': "You didn't select a choice.",
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse('polls:results', args=(question.id,)))

# def high():
#     highAnswer = topChoice()
#     return highAnswer

mysite/players/templates/players/add_player.html
{% load staticfiles %}
<head>
<link rel="stylesheet" type="text/css" href="{% static 'players/style.css' %}" />
<link href="//fonts.googleapis.com/css?family=Lobster&subset=latin,latin-ext" rel="stylesheet" type="text/css">
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
    <link rel="stylesheet" type="text/css" href="{% static 'players/addcss.css' %}" />
</head>
<div class ="page-header">
<h1>Add a new player  <img src="{% static 'players/images/tottenham1.png' %}" id="logo1" ></h1>
</div>
<form action="" method="post">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Save" />
</form>

mysite/players/templates/players/confirm_delete.html
{% load staticfiles %}
<link rel="stylesheet" type="text/css" href="{% static 'players/style.css' %}" />
<link href="//fonts.googleapis.com/css?family=Lobster&subset=latin,latin-ext" rel="stylesheet" type="text/css">
<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
<link rel="stylesheet" type="text/css" href="{% static 'players/addcss.css' %}" />
</head>
<div class ="page-header">
    <h1>Delete Player  <img src="{% static 'players/images/tottenham1.png' %}" id="logo1" ></h1>
</div>
<form method="post">{% csrf_token %}
    Are you sure you want to delete "{{ object }}" ?
    <input type="submit" value="Submit" />
</form>

mysite/players/templates/players/index.html
{% load staticfiles %}
<html>
<head>
<link rel="stylesheet" type="text/css" href="{% static 'players/style.css' %}" />
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
    <link href="//fonts.googleapis.com/css?family=Lobster&subset=latin,latin-ext" rel="stylesheet" type="text/css">

</head>
<div class="container">
    <div class="page-header">
        <h2>Tottenham Players Database  <img src="{% static 'players/images/tottenham1.png' %}" id="logo1" ></h2>

    </div>
    <input type="text" id="myInput" onkeyup="myFunction()" placeholder="Search by Surnames..">
    <span class = "bb1">
        <a href="{% url 'players:add' %}"><button type="button" class="button1">Add new player</button></a>
        </span>
    <span class = "bb2">
    <a href="{% url 'polls:index' %}"><button type="button" class="button1">Vote on your favourite players</button></a>
</span>

<br>
    <br>
<table class="hoverTable" id="myTable">
    <tr class="header">
        <th>First name</th>
        <th>Surname</th>
        <th>Shirt Number</th>
        <th>Age</th>
        <th>Position</th>
        <th>Goals scored this season (16/17)</th>
        <th>Date Joined</th>
        <th>Delete Field</th>
        <th>Edit Field</th>

    </tr>
    {% for player in player_list %}
    <tr>
        <td> {{ player.forename }} </td>
        <td>{{ player.player_name }}</td>
        <td>{{ player.shirt_number }} </td>
        <td>{{ player.player_age}} </td>
        <td>{{ player.player_position}} </td>
        <td>{{ player.goals_this_season}} </td>
        <td>{{ player.date_joined}} </td>
        <td><a href="{% url 'players:player_delete' player.pk %}"> Delete </a></td>
        <td><a href="{% url 'players:player_update' player.pk %}"> Edit </a></td>
    </tr>
    {% endfor %}
</table>
</div>
<script src="{% static 'players/js/table.js' %}" type="text/javascript"></script>
</html>

mysite/players/templates/players/update_form.html
{% load staticfiles %}
<head>
    <link rel="stylesheet" type="text/css" href="{% static 'players/style.css' %}" />
    <link href="//fonts.googleapis.com/css?family=Lobster&subset=latin,latin-ext" rel="stylesheet" type="text/css">
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
    <link rel="stylesheet" type="text/css" href="{% static 'players/addcss.css' %}" />
</head>
<div class ="page-header">
<h1>Edit Player  <img src="{% static 'players/images/tottenham1.png' %}" id="logo1" ></h1>
</div>
<form method="post">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Submit" />
</form>

mysite/polls/templates/polls/allresults.html
{% load staticfiles %}
<head>
    <link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}" />
    <link href="//fonts.googleapis.com/css?family=Lobster&subset=latin,latin-ext" rel="stylesheet" type="text/css">
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
</head>
<div class="page-header">

    <h1>Results</h1>


        {{ question.question_text }}

mysite/polls/templates/polls/detail.html
{% load staticfiles %}
<link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}" />
<link href="//fonts.googleapis.com/css?family=Lobster&subset=latin,latin-ext" rel="stylesheet" type="text/css">
<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
<div class="page-header">
<h1>{{ question.question_text }}  <img src="{% static 'players/images/tottenham1.png' %}" id="logo1" ></h1>
</div>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'polls:vote' question.id %}" method="post">
{% csrf_token %}
{% for choice in question.choice_set.all %}
    <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}" />
    <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br />
{% endfor %}
<input id="vote" type="submit" value="Vote" />
</form>

mysite/polls/templates/polls/index.html
<html>


{% load staticfiles %}
<head>
    <link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}" />
    <link href="//fonts.googleapis.com/css?family=Lobster&subset=latin,latin-ext" rel="stylesheet" type="text/css">
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
</head>
<div class ="page-header">
    <h1>Some Questions About Tottenham  <img src="{% static 'players/images/tottenham1.png' %}" id="logo1" ></h1>
</div>
{% if latest_question_list %}
    <ul>
    {% for question in latest_question_list %}
        <li><h2><a href="{% url 'polls:detail' question.id %}">{{ question.question_text }}</a></h2></li>
    {% endfor %}
	</ul>

{% else %}
    <p>No polls are available.</p>
{% endif %}
<span class = "bb2">
<a href="{% url 'players:index' %}"><button type="button" class="button1">Tottenham Players Database</button></a>
</span>
</html>

mysite/polls/templates/polls/results.html
{% load staticfiles %}
<head>
    <link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}" />
    <link href="//fonts.googleapis.com/css?family=Lobster&subset=latin,latin-ext" rel="stylesheet" type="text/css">
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
</head>
<div class="page-header">
<h1>{{ question.question_text }}  <img src="{% static 'players/images/tottenham1.png' %}" id="logo1" ></h1>
</div>
<ul>
{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
{% endfor %}
</ul>

<h1>
    Top Answer:
    {{ high_text }}
</h1>
<h2></h2>
<a href="{% url 'polls:detail' question.id %}"><button type="button" class="button1">Vote again?</button></a>
<a href="{% url 'polls:index' %}"><button type="button" class="button1">Home</button></a>